name: Fahad's CI
run-name: Name for the workflow generated
on: [pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      services: ${{ steps.filter.outputs.sample_1_libs }}
      sample_2: ${{ steps.filter.outputs.sample_2 }}
    steps:
    - uses: actions/checkout@v3 # necessary?
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          sample_1_libs:
            - 'sample_1/libs/**'
          sample_1_projects:
            - 'sample_1/projects/**'
          sample_2:
            - 'sample_2/**'
    - run: echo "sample1 ${{toJSON(steps.filter)}}"
