name: Fahad's CI
run-name: Name for the workflow generated
on: [pull_request]
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      lib-one-output: ${{ steps.filter.outputs.lib-one }}
      sample_2: ${{ steps.filter.outputs.sample_2 }}
      changes_arr: ${{steps.filter.outputs.changes}}
    steps:
      - uses: actions/checkout@v3 # necessary?
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lib-one:
              - 'sample_1/libs/lib-one/**'
            lib-two:
              - 'sample_1/libs/lib-two/**'
            sample_2:
              - 'sample_2/**'
      - run: echo "steps.filter ${{toJSON(steps.filter)}}"

  results:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - run: echo "changes output ${{toJSON(needs.changes.outputs)}}"
